### ISSUE TITLE
Changing User-Agent

### ISSUE THREAD

**Issue by MarcDee91** [clearthesky/requests#10]
At first: Really nice project!

I have tried to change the User-Agent via:
```

Map<String, String> params = new HashMap<>();
		params.put("User-Agent", "Mozilla/5.0 (Windows NT 6.0; rv:2.0.1) Gecko/20100101 Firefox/4.0.1");
System.out.println(net.dongliu.requests.Requests.get("http://localhost:2343/init.aspx").headers(params).send().readToText());
```
But it doesn't seem to work: The User-Agent is Requests/4.0, Java 1.8.0 

So is it possible to change the agent?

**Comment by clearthesky** [comment]
This code do change user-agent for me. Which version you are using?
Or you can try 
```java
Requests.get(url).userAgent("Mozilla/5.0 (Windows NT 6.0; rv:2.0.1) Gecko/20100101 Firefox/4.0.1")
```

**Comment by MarcDee91** [comment]
Thanks for replying!

I am using the latest version from the central maven repo. --> 4.7.1 
I have tried your solution, but it doesn't seem to work! ( I have used www.whoishostingthis.com for getting the user-agent)

`System.out.println(net.dongliu.requests.Requests.get("http://www.whoishostingthis.com/tools/user-agent").userAgent("Mozilla/5.0 (Windows NT 6.0; rv:2.0.1) Gecko/20100101 Firefox/4.0.1").send().readToText());`

Does this work for you ?

**Comment by clearthesky** [comment]
The site redirect http://www.whoishostingthis.com/tools/user-agent to http://www.whoishostingthis.com/tools/user-agent/, seems Requests does not use the specified user-agent when send the redirected http request. I will fix this later.
For now, using Requests.get("http://www.whoishostingthis.com/tools/user-agent/") you can get the expected result.

**Comment by MarcDee91** [comment]
Hey thanks, I will test it when the maven repo is up-to-date!

**Comment by clearthesky** [comment]
Now you can try version 4.7.2, set user agent by .userAgent("Mozilla/5.0 (Windows NT 6.0; rv:2.0.1) Gecko/20100101 Firefox/4.0.1")
