### ISSUE TITLE
verify

### ISSUE THREAD

**Issue by berlinsaint** [clearthesky/requests#12]
https的verify貌似设置false貌似无效啊 ，
我ip地址访问https 网站始终不ok。

**Comment by berlinsaint** [comment]
UrlconnectionExcuetor.java 文件 添加 对hostnameverifier的支持；
       HostnameVerifier customHv = new HostnameVerifier() {  
            public boolean verify(String urlHostName, SSLSession session) {  
                System.out.println("Warning: URL Host: " + urlHostName + " vs. "  
                                   + session.getPeerHost());  
                return true;  
            }  
        }; 

然后在 ssf!=null 判断后添加
((HttpsURLConnection) conn).setHostnameVerifier(customHv);

**Comment by berlinsaint** [comment]
作者能将上面解决方法 合并下么，用你的 requests库，懒得改maven地址了 重新发个版本吧！

**Comment by clearthesky** [comment]
嗯，可以的，我改一下

**Comment by clearthesky** [comment]
新版本4.7.5，加入了这个修改
