### ISSUE TITLE
我又来了【java8 ?】

### ISSUE THREAD

**Issue by berlinsaint** [clearthesky/requests#13]
作者大大，上次给你提了 hostnamerverify的问题，今天我又来找事了。。。
我想问下  这个代码 是哪里用了java8的 新特性 非要支持java8么，我们做平台化的 ，需要覆盖至少java7，想拿你这个代码修改，想了解下，你这个requests支持jdk7 难度有多大，或者您顺手也支持下 7呗。。多谢。。。。。

**Comment by clearthesky** [comment]
曾经在设计API的时候，用到了interface的default method特性，当时就切到java8了。现在的API不再依赖这个特性了，转回Java7应该是没问题的。
有时间我切回去，应该不需要什么代码修改.

**Comment by berlinsaint** [comment]
好的 期待您尽快 转个java7 吧，我先再本地 看看 怎么修改下。。。我们后面希望长期使用你这个 项目，还是希望走你的maven。我是本地测试没问题，部署到用户那 只能1.7版本，崩溃了，定位半天 是 jdk版本问题。。。。 换3的话 发现 api改动还是有一点的。。还是想用你最新的版本，我自己先看看怎么编一个1.7的jar。。。。多谢，长期关注requests~我是python转过来的。。。用惯了requests。。。。

**Comment by berlinsaint** [comment]
我看了下 用了比较多的 流式计算类的，。。我去。。改起来挺费事，，虽然很帅气。。。。。。。。我了个去。。。我去。。。

**Comment by clearthesky** [comment]
有一些用到了stream的要改。
新发了版本4.8.0，可以在Java7种使用了。

**Comment by berlinsaint** [comment]
我曹  太牛逼了  太迅速了 。。。。。··多谢大大 。。。正发愁呢，，今天发版本。。。太感谢！！
