### ISSUE TITLE
requests.session实现不了吗

### ISSUE THREAD

**Issue by GaoDongWan** [clearthesky/requests#15]
这是主页
https://so.dajie.com/job/search  
这是一个ajax页
https://so.dajie.com/job/ajax/search/filter?keyword=python&order=0&city=&recruitType=&salary=&experience=&page=1&positionFunction=&_CSRFToken=&ajax=1
访问主页会反回一个cookie，之后带着这个cookie才能访问ajax页，但不能另外打开新页访问ajax页。python里的requests.session可以实现通过访问主页在访问ajax页，从而拿到json数据
但是这里的session功能没能成功访问抓取ajax数据
有什么解决方法么

**Comment by clearthesky** [comment]
不是cookie的问题，是缺少Referrer Header
ession.get(ajaxUrl).headers(
            Parameter.of("Referer", url),
            Parameter.of("Accept", "application/json, text/javascript, */*; q=0.01")
    ).send().readToText()
这样就可以.

**Comment by GaoDongWan** [comment]
可以抓到了，谢谢大佬
