### ISSUE TITLE
IndexOutOfBoundException when set cookies

### ISSUE THREAD

**Issue by Jamling** [clearthesky/requests#17]
ver: 4.9.0
file: URLConnectionExecutor
loc: line:163
```java
        // set cookies
        if (!request.getCookies().isEmpty() || !session.getCookies().isEmpty()) {
            StringBuilder sb = new StringBuilder();
            for (Map.Entry<String, ?> entry : request.getCookies()) {
                sb.append(entry.getKey()).append("=").append(String.valueOf(entry.getValue())).append(";");
            }
            for (Cookie cookie : session.matchedCookies(protocol, host, effectivePath)) {
                sb.append(cookie.getName()).append("=").append(cookie.getValue()).append(";");
            }
// exception when sb.length is 0;
            String cookieStr = sb.deleteCharAt(sb.length() - 1).toString();
            if (!cookieStr.isEmpty()) {
                conn.setRequestProperty(NAME_COOKIE, cookieStr);
            }
        }
```
PS: request 2.1.5 works well for me, but error when it's upgraded to 4.9.0

I tried to set cookies from last response to current request, but the server answered logic error.

**Comment by Jamling** [comment]
After upgraded to 4.9.1, the server return auth error. I think it may be some problem with the cookie.

**Comment by clearthesky** [comment]
could you provide more details? such as urls, Set-Cookie header in response, and the cookie send by requests client.

**Comment by Jamling** [comment]
Please see the SmartQQ protocol login. [step 2, get ptwebqq](http://www.scienjus.com/webqq-analysis-2/). The verify qrcode reponse return lots of cookie, and there domain has (ssl.ptlogin2.qq.com, qq.com, d1.web.qq.com, s2.web.qq.com ... ) and when I request to fetch ptwebqq,  session.matchedCookies return empty list. So the server answer me an error code.

**Comment by clearthesky** [comment]
I follow the article and failed at get https://ssl.ptlogin2.qq.com/ptqrlogin?....
For those two get requests, session cookies works well.
After inspecting the webqq login requests, It seems that webqq has changed qrcode login url parameters, added one new parameter ptqrlogin.You should not login successfully without this parameter.

**Comment by Jamling** [comment]
The qrcode login and verify works well for both of v2.1.5 and 4.9.1
I failed on get ptwebqq, the right logic is return the ptwebqq but error code 100000 returned to me.

**Comment by clearthesky** [comment]
The article is a little outdate, i check the latest source code in the repo by the article's author, https://github.com/ScienJus/smartqq/blob/java8/src/main/java/com/scienjus/smartqq/client/SmartQQClient.java#L149 , with this i can proceed the login process and find the problem. 

When cookie value ends with ';',  request cannot deal with it rightly. I'll fix it soon.

**Comment by Jamling** [comment]
Yes,  I try to develop a plugin for IDE (Eclipse and Intellij Idea) base on SmartQQ.
Another question, the request can works well on Android Platform?

**Comment by clearthesky** [comment]
The only dependency is UrlConnection, so it should work on android too.

**Comment by Jamling** [comment]
Thank you! I tried to use 4.9.2, it return me the html of referer when get ptwebqq :(.

**Comment by clearthesky** [comment]
To get response other than the html content, use xxxx.send().toTextResponse();
And there is no way to dump request now.

**Comment by Jamling** [comment]
Here is the request dump of 4.9.2 when get ptwebqq, I'll dump the request of 2.1.5 later 
request : http://ptlogin2.web2.qq.com/check_sig?pttype=1&uin=157250921&service=ptqrlogin&nodirect=0&ptsigx=ea1c7dabe35eeb3256ee1e57b78a89e478b7531966af2ba6ed8c5428853a2c36c3ee86b5400fda830e9cc9c8c20db0c7dc13b479b072b7b2858f414f2f153f4b&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&f_url=&ptlang=2052&ptredirect=100&aid=501004106&daid=164&j_later=0&low_login_hour=0&regmaster=0&pt_login_type=3&pt_aid=0&pt_aaid=16&pt_light=0&pt_3rd_aid=0
cookie : [Cookie{domain='.ptlogin2.qq.com', path='/', name='superuin', value='o0157250921', expiry=0}, Cookie{domain='.qq.com', path='/', name='skey', value='@PMjEj0VFb', expiry=0}, Cookie{domain='.qq.com', path='/', name='ptisp', value='ctc', expiry=0}, Cookie{domain='.qq.com', path='/', name='uin', value='o0157250921', expiry=0}, Cookie{domain='.qq.com', path='/', name='pt2gguin', value='o0157250921', expiry=1577923200000}, Cookie{domain='.ptlogin2.qq.com', path='/', name='supertoken', value='2270874487', expiry=0}, Cookie{domain='.ptlogin2.qq.com', path='/', name='ptnick_157250921', value='e6988ee69c88', expiry=0}, Cookie{domain='.ptlogin2.qq.com', path='/', name='ETK', value='', expiry=0}, Cookie{domain='.ptlogin2.qq.com', path='/', name='superkey', value='lyd*UQZTZWdY5k*UGE270Bklgl9PsTGt0pUkRUhbur0_', expiry=0}, Cookie{domain='.qq.com', path='/', name='RK', value='iUdCAZMLYx', expiry=1813910038000}, Cookie{domain='.qq.com', path='/', name='ptwebqq', value='0f387cd03b7a9612485d3c7b0d010bd849f2c83a9ab34cdd73181854565f5099', expiry=0}, Cookie{domain='.ptlogin2.qq.com', path='/', name='pt_recent_uins', value='8d58ac68fb5604f67ace20a889df3326ef766c00413875fbad9c72bc0289cdef7ac7a4cf7a5dd0819bb16d1b1a7fcd6df5f0a5b03b8f26ef', expiry=1501142038000}]
header: [(User-Agent = Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36)]

**Comment by Jamling** [comment]
here is the request of 2.1.5 detail info.

request : http://ptlogin2.web2.qq.com/check_sig?pttype=1&uin=157250921&service=ptqrlogin&nodirect=0&ptsigx=47a7dac1e5bcdf90a963839d06c1b83a229294636beb30016f247b83b90881fafbc3bd39fde141cb0045b764acc804ea1fb44771419bff0d3c5fc38c2274f069&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&f_url=&ptlang=2052&ptredirect=100&aid=501004106&daid=164&j_later=0&low_login_hour=0&regmaster=0&pt_login_type=3&pt_aid=0&pt_aaid=16&pt_light=0&pt_3rd_aid=0
cookie : null
header: [User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36]

**Comment by Jamling** [comment]
It seem there is no problem of cookies. But I don't known the why the problem occured.

**Comment by clearthesky** [comment]
you mean get the ptwebqq cookie?
for testing i wrote a example, it works well.

```java
package net.dongliu.requests;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {

    private static int hash33(String str) {
        int e = 0, i = 0, n = str.length();
        for (; n > i; ++i)
            e += (e << 5) + str.charAt(i);
        return 2147483647 & e;
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        String qrCodeUrl = "https://ssl.ptlogin2.qq.com/ptqrshow?appid=501004106&e=0&l=M&s=5&d=72&v=4&t=0.12899027792406392";

        Session session = Requests.session();
        Response<byte[]> qrResp = session.get(qrCodeUrl).send().toBytesResponse();
        Files.write(Paths.get("qq_qr.png"), qrResp.getBody());
        Runtime.getRuntime().exec("open qq_qr.png");

        String qrsig = qrResp.getFirstCookie("qrsig").getValue();
        int ptqrtoken = hash33(qrsig);
        String checkSigUrl;
        String ptwebqq;
        Pattern pattern = Pattern.compile("'(http[^']+)'");
        while (true) {
            String qrCodeStatusUrl = "https://ssl.ptlogin2.qq.com/ptqrlogin?ptqrtoken=" + ptqrtoken + "&webqq_type=10&remember_uin=1&login2qq=1&aid=501004106&u1=http%3A%2F%2Fw.qq.com%2Fproxy.html%3Flogin2qq%3D1%26webqq_type%3D10&ptredirect=0&ptlang=2052&daid=164&from_ui=1&pttype=1&dumy=&fp=loginerroralert&action=0-0-8861&mibao_css=m_webqq&t=1&g=1&js_type=0&js_ver=10222&login_sig=&pt_randsalt=3";
            Response<String> loginResp = session.get(qrCodeStatusUrl).send().toTextResponse();
            Matcher matcher = pattern.matcher(loginResp.getBody());
            if (matcher.find()) {
                checkSigUrl = matcher.group(1);
                ptwebqq = loginResp.getFirstCookie("ptwebqq").getValue();
                System.out.println("checkSigUrl: " + checkSigUrl);
                break;
            }
            Thread.sleep(1000);
        }

        String proxyUReferer = "http://s.web2.qq.com/proxy.html?v=20130916001&callback=1&id=1";
        Response<String> proxyResp = session.get(checkSigUrl)
                .headers(Parameter.of("Referer", proxyUReferer))
                .followRedirect(false).send().toTextResponse();
        System.out.println(ptwebqq);

    }
}

```

**Comment by Jamling** [comment]
I run your test, it works well for me! 
I am so puzzled ~, I'll try to find the cause.

**Comment by Jamling** [comment]
If I remove the user-agent header, my code works well as some as yours, but failed in step login.

```java
String proxyUReferer = "http://s.web2.qq.com/proxy.html?v=20130916001&callback=1&id=1";
        Response<String> proxyResp = session.get(checkSigUrl)
                .headers(Parameter.of("Referer", proxyUReferer))
                .followRedirect(false).send().toTextResponse();
        System.out.println("ptwebqq:" + ptwebqq);
        
        String vfwebqqUrl = "https://s.web2.qq.com/api/getvfwebqq?ptwebqq={1}&clientid=53999199&psessionid=&t=0.1";
        Response<String> vfwebqqResp = session
                .get(vfwebqqUrl.replace("{1}", ptwebqq))
                .headers(Parameter.of("Referer", proxyUReferer))
                .followRedirect(false).send().toTextResponse();
        String vfwebqqJson = vfwebqqResp.getBody();
        String vfwebqq = getJson(vfwebqqJson).getJSONObject("result")
                .getString("vfwebqq");
        System.out.println("vfwebqq:" + vfwebqq);
        
        JSONObject r = new JSONObject();
        r.put("ptwebqq", ptwebqq);
        r.put("clientid", "53999199");
        r.put("psessionid", "");
        r.put("status", "online");
        
        proxyUReferer = "http://s.web2.qq.com/proxy.html?v=20130916001&callback=1&id=2";
        Response<String> response = session
                .post("http://d1.web2.qq.com/channel/login2")
                .headers(Parameter.of("Referer", proxyUReferer))
                .headers(
                        Parameter.of("Origin", "http://d1.web2.qq.com/channel"))
                .params(Parameter.of("r", r.toJSONString())).send()
                .toTextResponse();
        System.out.println(response.getBody());
        JSONObject result = getJson(response.getBody()).getJSONObject("result");
        String psessionid = result.getString("psessionid");
        long uin = result.getLongValue("uin");
        System.out.println(uin);
```

The return of http://d1.web2.qq.com/channel/login2 is
{"errmsg":"error!!!","retcode":100001}

**Comment by Jamling** [comment]
我将底层连接替换为okhttp，发现仍然存在问题，继而使用Wireshark抓包，奇怪的是getvfwebqq这个请求并没有抓到。所以我不敢100%肯定，只能猜测，request4.9.2中get ptwebqq这一步返回异常是由于cookie的顺序导致的。
