### ISSUE TITLE
请求支持 fastjson

### ISSUE THREAD

**Issue by tastypear** [clearthesky/requests#7]
看到原生支持 gson 和 jackson，是否考虑加上 fastjson

**Comment by clearthesky** [comment]
可以加上
我对fastjson不太熟，fastjson序列化的时候不能写到Writer, 反序列化的时候也不能从Reader读取，目前和抽取的处理json数据的API不一致。不知道有没有好的办法

**Comment by ScienJus** [comment]
`JSON.parseObject(Inputstream, Type)` （是的，没有 `Reader` 只有 `Inputstream`）和 `JSON.writeJSONString(Writer, Object)` 应该可以勉强满足？

**Comment by clearthesky** [comment]
加上了，试试4.6.6

**Comment by tastypear** [comment]
效果拔群
